name: tubes_traveloka
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2+1
  path: ^1.8.0
  intl: ^0.17.0
  pdf: ^3.7.3
  printing: ^5.7.4
  path_provider: ^2.0.9
  google_fonts: ^6.2.1 # Tambahkan ini
  flutter_staggered_animations: ^1.1.1 # Tambahkan ini

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
